version: '3'
services:
  shortenurl:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: production
    container_name: shortenurl
    environment:
     - SERVICE_ENV=local
     - LOGLEVEL=debug
    image: prdocker:shortenurl
    ports:
     - "8080:8080"